import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const rootDir = path.resolve(fileURLToPath(import.meta.url), '../..');
const pkg = JSON.parse(execSync('npm pkg get version', { cwd: rootDir }).toString());

function git(command, fallback) {
  try {
    return execSync(command, { cwd: rootDir }).toString().trim();
  } catch {
    return fallback;
  }
}

const commitCount = git('git rev-list --count HEAD', '0');
const gitSha = git('git rev-parse --short HEAD', 'unknown');
const buildVersion = `${pkg}+${commitCount}.${gitSha}`;

const output = `// Auto-generated by scripts/generateVersion.mjs on every build — do not edit, do not commit.
export const PACKAGE_VERSION = '${pkg}';
export const COMMIT_COUNT = '${commitCount}';
export const GIT_SHA = '${gitSha}';
export const BUILD_VERSION = '${buildVersion}';
`;

writeFileSync(path.join(rootDir, 'src/config/version.ts'), output);
console.log(`Generated src/config/version.ts — ${buildVersion}`);
